$axure.loadCurrentPage({
  "url":"业务主任项目列表.html",
  "generationDate":new Date(1453298469234.95),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f7f2598c6f374cce86296b8f45d56554",
    "type":"Axure:Page",
    "name":"业务主任项目列表",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"bdac2bede3c046fbb0c98f54e57ebaa5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":120},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9d914d119504e9b979cf863b4bb708b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":120},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7f3c2d6eaba54633bb0a67150ab6b81c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":540,
              "y":120},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a6b2789977a4b68b6e5c023fca18e40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":540,
                  "y":120},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7c385e5737e145b0b0361448837340ef",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":120},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b6ad009eb08945e4963a32554bb4de06",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":610,
              "y":115.5},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"71ba6cda0a8b45e98f4e99dacbf77cf4",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":870,
              "y":170},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"9c8b5451d67d4f668104cc93c63757c2",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":240},
            "size":{
              "width":790,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7a638459538429598e96c2b0c30dfdc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":158,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"70d1b8dcba004f2d89e8b5b58bd3bf28",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":158,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务主任项目列表/u8.png"}},
{
              "id":"1a7162c4aa844255bd0f25c973acf995",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":158,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"98b751df9abc42b8aaf4e279ce57b97c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":158,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "interactionMap":{
                "onClick":{
                  "description":"OnClick",
                  "cases":[{
                      "description":"用例 1",
                      "isNewIfGroup":false,
                      "actions":[{
                          "action":"linkWindow",
                          "description":"在 新窗口/标签页 打开 项目详细页面",
                          "target":{
                            "targetType":"page",
                            "url":"项目详细页面.html",
                            "includeVariables":true},
                          "linkType":"new"}]}]}},
              "tabbable":true,
              "images":{
                "normal~":"images/业务主任项目列表/u8.png"}},
{
              "id":"54681719cc7946febd63a2804f6a759e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":158,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0a3d1e69f3784531a79f71da7631ee10",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":158,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务主任项目列表/u28.png"}},
{
              "id":"1d53cbee0e0445dd9d55385ea8f78caa",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":158,
                  "y":0},
                "size":{
                  "width":158,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f96ebc4addc14eda95ca41926e9a65fc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":158,
                      "y":0},
                    "size":{
                      "width":158,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务主任项目列表/u8.png"}},
{
              "id":"40476b86cccb4ec5986d3722983c7025",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":158,
                  "y":30},
                "size":{
                  "width":158,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"50068fb183404a54b42dd9428a98e4f0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":158,
                      "y":30},
                    "size":{
                      "width":158,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务主任项目列表/u8.png"}},
{
              "id":"f74ab099eab34d8a94c176ceb590c403",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":158,
                  "y":60},
                "size":{
                  "width":158,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"65f789236b184756af497e45cb56aca6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":158,
                      "y":60},
                    "size":{
                      "width":158,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务主任项目列表/u28.png"}},
{
              "id":"0a19da95fcb247fb8da4a126bb5f5304",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":316,
                  "y":0},
                "size":{
                  "width":158,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5c9b5166dbfa45438bcc2f7d2d653db2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":316,
                      "y":0},
                    "size":{
                      "width":158,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务主任项目列表/u8.png"}},
{
              "id":"63561370dd864df994e4385c7e98002b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":316,
                  "y":30},
                "size":{
                  "width":158,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"29a5289f961345ab98d3cd8fa305bd8d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":316,
                      "y":30},
                    "size":{
                      "width":158,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务主任项目列表/u8.png"}},
{
              "id":"6ea32a270cb6407899962aeb247726c5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":316,
                  "y":60},
                "size":{
                  "width":158,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"da3a70b61d924f75a38230726e5f0a8d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":316,
                      "y":60},
                    "size":{
                      "width":158,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务主任项目列表/u28.png"}},
{
              "id":"a3757031afe1403f91f92e2b2dc5a2c5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":632,
                  "y":0},
                "size":{
                  "width":158,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3e266565d9184c5f98e243eb904e247c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":632,
                      "y":0},
                    "size":{
                      "width":158,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务主任项目列表/u16.png"}},
{
              "id":"358e18641fe5400ca1fb5f0695fe5f97",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":632,
                  "y":30},
                "size":{
                  "width":158,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"87709d9ddd5a4ff5987c1c4cacf5f68c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":632,
                      "y":30},
                    "size":{
                      "width":158,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务主任项目列表/u16.png"}},
{
              "id":"ce9ed01d1fd94a6097e708fd84409b74",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":632,
                  "y":60},
                "size":{
                  "width":158,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"273f47e6c70848e8bf03f6087f7739e7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":632,
                      "y":60},
                    "size":{
                      "width":158,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务主任项目列表/u36.png"}},
{
              "id":"a60c0e92016e41e79566bb8a9d22189b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":474,
                  "y":0},
                "size":{
                  "width":158,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1a1c296d0f7b4f698c64ffcdaa3ca755",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":474,
                      "y":0},
                    "size":{
                      "width":158,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务主任项目列表/u8.png"}},
{
              "id":"aa3033a541b44bb5aba5a21bad299852",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":474,
                  "y":30},
                "size":{
                  "width":158,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d778744b47d14e7fba8eba2d6fa7a661",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":474,
                      "y":30},
                    "size":{
                      "width":158,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务主任项目列表/u8.png"}},
{
              "id":"d22d8ff23f5247b9a8ff088fe7283a7d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":474,
                  "y":60},
                "size":{
                  "width":158,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9fb537e998234879a43c3eda7f6a3c7a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":474,
                      "y":60},
                    "size":{
                      "width":158,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务主任项目列表/u28.png"}}]},
{
          "id":"bed559d9c7344aed84435bedae227f42",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":870,
              "y":205},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 业务主任分配负责人",
                      "target":{
                        "targetType":"page",
                        "url":"业务主任分配负责人.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"9a8c9e746c08462bbf040bd3ef81402d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":150,
              "y":34},
            "size":{
              "width":129,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4f35b28b85c45d391750ec8bddf7274",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":150,
                  "y":34},
                "size":{
                  "width":129,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "bdac2bede3c046fbb0c98f54e57ebaa5":{
      "scriptId":"u0"},
    "b9d914d119504e9b979cf863b4bb708b":{
      "scriptId":"u1"},
    "7f3c2d6eaba54633bb0a67150ab6b81c":{
      "scriptId":"u2"},
    "6a6b2789977a4b68b6e5c023fca18e40":{
      "scriptId":"u3"},
    "7c385e5737e145b0b0361448837340ef":{
      "scriptId":"u4"},
    "b6ad009eb08945e4963a32554bb4de06":{
      "scriptId":"u5"},
    "71ba6cda0a8b45e98f4e99dacbf77cf4":{
      "scriptId":"u6"},
    "9c8b5451d67d4f668104cc93c63757c2":{
      "scriptId":"u7"},
    "b7a638459538429598e96c2b0c30dfdc":{
      "scriptId":"u8"},
    "70d1b8dcba004f2d89e8b5b58bd3bf28":{
      "scriptId":"u9"},
    "1d53cbee0e0445dd9d55385ea8f78caa":{
      "scriptId":"u10"},
    "f96ebc4addc14eda95ca41926e9a65fc":{
      "scriptId":"u11"},
    "0a19da95fcb247fb8da4a126bb5f5304":{
      "scriptId":"u12"},
    "5c9b5166dbfa45438bcc2f7d2d653db2":{
      "scriptId":"u13"},
    "a60c0e92016e41e79566bb8a9d22189b":{
      "scriptId":"u14"},
    "1a1c296d0f7b4f698c64ffcdaa3ca755":{
      "scriptId":"u15"},
    "a3757031afe1403f91f92e2b2dc5a2c5":{
      "scriptId":"u16"},
    "3e266565d9184c5f98e243eb904e247c":{
      "scriptId":"u17"},
    "1a7162c4aa844255bd0f25c973acf995":{
      "scriptId":"u18"},
    "98b751df9abc42b8aaf4e279ce57b97c":{
      "scriptId":"u19"},
    "40476b86cccb4ec5986d3722983c7025":{
      "scriptId":"u20"},
    "50068fb183404a54b42dd9428a98e4f0":{
      "scriptId":"u21"},
    "63561370dd864df994e4385c7e98002b":{
      "scriptId":"u22"},
    "29a5289f961345ab98d3cd8fa305bd8d":{
      "scriptId":"u23"},
    "aa3033a541b44bb5aba5a21bad299852":{
      "scriptId":"u24"},
    "d778744b47d14e7fba8eba2d6fa7a661":{
      "scriptId":"u25"},
    "358e18641fe5400ca1fb5f0695fe5f97":{
      "scriptId":"u26"},
    "87709d9ddd5a4ff5987c1c4cacf5f68c":{
      "scriptId":"u27"},
    "54681719cc7946febd63a2804f6a759e":{
      "scriptId":"u28"},
    "0a3d1e69f3784531a79f71da7631ee10":{
      "scriptId":"u29"},
    "f74ab099eab34d8a94c176ceb590c403":{
      "scriptId":"u30"},
    "65f789236b184756af497e45cb56aca6":{
      "scriptId":"u31"},
    "6ea32a270cb6407899962aeb247726c5":{
      "scriptId":"u32"},
    "da3a70b61d924f75a38230726e5f0a8d":{
      "scriptId":"u33"},
    "d22d8ff23f5247b9a8ff088fe7283a7d":{
      "scriptId":"u34"},
    "9fb537e998234879a43c3eda7f6a3c7a":{
      "scriptId":"u35"},
    "ce9ed01d1fd94a6097e708fd84409b74":{
      "scriptId":"u36"},
    "273f47e6c70848e8bf03f6087f7739e7":{
      "scriptId":"u37"},
    "bed559d9c7344aed84435bedae227f42":{
      "scriptId":"u38"},
    "9a8c9e746c08462bbf040bd3ef81402d":{
      "scriptId":"u39"},
    "f4f35b28b85c45d391750ec8bddf7274":{
      "scriptId":"u40"}}});