$axure.loadCurrentPage({
  "url":"审核人项目列表.html",
  "generationDate":new Date(1453298203044.1),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"883859f3d78b4111bec881f5ab6cd204",
    "type":"Axure:Page",
    "name":"审核人项目列表",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0a2d8642df83405f836e56e95e09c090",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":120},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ea682922c8c4caeadb290924d23bf89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":120},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"02a26d111d7b410b8996a8dd8e9d5fba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":540,
              "y":120},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c360194812c04432b0fe8d3a4bc59ffc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":540,
                  "y":120},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f5d9d10e08fc4d2f84f957a4d6c0d05b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":120},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"ad356957b4914f1c8aaf3857aaea9801",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":610,
              "y":115.5},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"a006e87605394e87b5666c1c505e8597",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":960,
              "y":165},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"75e48869643946848f145b4f05cf73a2",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":168,
              "y":260},
            "size":{
              "width":1249,
              "height":84}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23912209450e4dbbb2dca0135ebdc244",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":178,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"74a92c7bf5494f84b72eaf9b01c7bee6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":178,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/经营主任项目列表/u8.png"}},
{
              "id":"1135e562514148789eaf83131aff7004",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":178,
                  "height":24}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a411ea16b1154fc7bd75c4a621ecd16f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":178,
                      "height":24}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/审核人项目列表/u22.png"}},
{
              "id":"d246f10d0f3546358dd3fa9edfce863d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":54},
                "size":{
                  "width":178,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fe636960f63042e39af79e11c286fccf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":54},
                    "size":{
                      "width":178,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/经营主任项目列表/u28.png"}},
{
              "id":"8fc5ff3ae11a4c8ab338de8131123667",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":178,
                  "y":0},
                "size":{
                  "width":178,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7d018832e2f548299affbbe856ed8d6b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":178,
                      "y":0},
                    "size":{
                      "width":178,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/经营主任项目列表/u8.png"}},
{
              "id":"c99cc9531add425ca1638d7de627acc6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":178,
                  "y":30},
                "size":{
                  "width":178,
                  "height":24}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4fff8d70cbb946b5a37554230f622953",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":178,
                      "y":30},
                    "size":{
                      "width":178,
                      "height":24}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/审核人项目列表/u22.png"}},
{
              "id":"e0ce4ca01073496ea9ccf75d7a23ff92",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":178,
                  "y":54},
                "size":{
                  "width":178,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1996307f27034fa2a7ef2831cd05f11e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":178,
                      "y":54},
                    "size":{
                      "width":178,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/经营主任项目列表/u28.png"}},
{
              "id":"374c6e90bf374a1faa4b0d207ecd796c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":356,
                  "y":0},
                "size":{
                  "width":178,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4acee0e63b0f45c2976dc5898a924af1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":356,
                      "y":0},
                    "size":{
                      "width":178,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/经营主任项目列表/u8.png"}},
{
              "id":"46361c48c22b45ca84e0559ab57aac85",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":356,
                  "y":30},
                "size":{
                  "width":178,
                  "height":24}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"89f95ce8074e494ea8ca2b2448c47b28",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":356,
                      "y":30},
                    "size":{
                      "width":178,
                      "height":24}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/审核人项目列表/u22.png"}},
{
              "id":"5763d4abc0b444eb8bb3a62dac0633e2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":356,
                  "y":54},
                "size":{
                  "width":178,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"457b2651f47e4b249a75be68e55e9412",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":356,
                      "y":54},
                    "size":{
                      "width":178,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/经营主任项目列表/u28.png"}},
{
              "id":"dc948c9c9d004f32965996a403d868ae",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":1068,
                  "y":0},
                "size":{
                  "width":181,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"55215d8c41df4755a39e57dc6793abf6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":1068,
                      "y":0},
                    "size":{
                      "width":181,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/审核人项目列表/u20.png"}},
{
              "id":"4de15a77519a41c099a2798177f262a8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":1068,
                  "y":30},
                "size":{
                  "width":181,
                  "height":24}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d3458a490a8d4afa959b6d809d1aa9e4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":1068,
                      "y":30},
                    "size":{
                      "width":181,
                      "height":24}},
                  "adaptiveStyles":{
}}],
              "interactionMap":{
                "onClick":{
                  "description":"OnClick",
                  "cases":[{
                      "description":"用例 1",
                      "isNewIfGroup":false,
                      "actions":[{
                          "action":"linkWindow",
                          "description":"在 弹出窗口 打开 审核人审核",
                          "target":{
                            "targetType":"page",
                            "url":"审核人审核.html",
                            "includeVariables":true},
                          "linkType":"popup",
                          "popup":{
                            "left":100,
                            "top":100,
                            "width":500,
                            "height":500,
                            "toolbar":false,
                            "scrollbars":false,
                            "location":false,
                            "status":false,
                            "menubar":false,
                            "directories":false,
                            "resizable":false,
                            "centerwindow":true}}]}]}},
              "tabbable":true,
              "images":{
                "normal~":"images/审核人项目列表/u34.png"}},
{
              "id":"d7fbcb5e02874fb4896710cc6286c84a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":1068,
                  "y":54},
                "size":{
                  "width":181,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6324e0a6c58748f299bfd128b4dee844",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":1068,
                      "y":54},
                    "size":{
                      "width":181,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/审核人项目列表/u48.png"}},
{
              "id":"375b7fd8e8c143559e1721807c960529",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":534,
                  "y":0},
                "size":{
                  "width":178,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3565cc6e0ec44ce48575076edf51f3c3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":534,
                      "y":0},
                    "size":{
                      "width":178,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/经营主任项目列表/u8.png"}},
{
              "id":"cc6ee2c36aa54085868c16aaf3f60034",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":534,
                  "y":30},
                "size":{
                  "width":178,
                  "height":24}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dff5fc3733e24d7d9c0f0166251a2cf3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":534,
                      "y":30},
                    "size":{
                      "width":178,
                      "height":24}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/审核人项目列表/u22.png"}},
{
              "id":"e013c08af5114123858883f6255e003b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":534,
                  "y":54},
                "size":{
                  "width":178,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4f022e5f41bf4212a3be16129c6b9da2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":534,
                      "y":54},
                    "size":{
                      "width":178,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/经营主任项目列表/u28.png"}},
{
              "id":"cbf2b7a7153c4bf4b82e79c4b0bd432a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":712,
                  "y":0},
                "size":{
                  "width":178,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ab880933b7cd46cd9cb1c10c0028bf53",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":712,
                      "y":0},
                    "size":{
                      "width":178,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/经营主任项目列表/u8.png"}},
{
              "id":"f58528ef17124c3f89e390fde1769049",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":712,
                  "y":30},
                "size":{
                  "width":178,
                  "height":24}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"751632f7fc374819a6b1e640729b8f29",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":712,
                      "y":30},
                    "size":{
                      "width":178,
                      "height":24}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/审核人项目列表/u22.png"}},
{
              "id":"578a934fb91a48508782d384c1b6f172",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":712,
                  "y":54},
                "size":{
                  "width":178,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d1e993d6434a4d9dbff970c47fe24ebc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":712,
                      "y":54},
                    "size":{
                      "width":178,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/经营主任项目列表/u28.png"}},
{
              "id":"1b10c1b0be764bed9ba3a01d82307fd8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":890,
                  "y":0},
                "size":{
                  "width":178,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"25d314fa89d54f06a907f13423b44b06",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":890,
                      "y":0},
                    "size":{
                      "width":178,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/经营主任项目列表/u8.png"}},
{
              "id":"8c44a594aa414883ac5ab81b94271924",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":890,
                  "y":30},
                "size":{
                  "width":178,
                  "height":24}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8c5c7c0ed9ff4f32a3e73fcaef6334d6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":890,
                      "y":30},
                    "size":{
                      "width":178,
                      "height":24}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/审核人项目列表/u22.png"}},
{
              "id":"694226f3f84e4189aa2cd389fb433c5d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":890,
                  "y":54},
                "size":{
                  "width":178,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"698e7761347947edb55a8839c5c613d4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":890,
                      "y":54},
                    "size":{
                      "width":178,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/经营主任项目列表/u28.png"}}]},
{
          "id":"c59bfc5096bb404c97fdae47b28d7105",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":238,
              "y":297},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98bdf73fe9f942be9008019d55f89d36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":238,
                  "y":297},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 项目详细页面",
                      "target":{
                        "targetType":"page",
                        "url":"项目详细页面.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"080b87c1f5fb483e95514c7c56dd12ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":160,
              "y":34},
            "size":{
              "width":113,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56dfa8cabf20405daa7397196981d2af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":160,
                  "y":34},
                "size":{
                  "width":113,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "0a2d8642df83405f836e56e95e09c090":{
      "scriptId":"u0"},
    "1ea682922c8c4caeadb290924d23bf89":{
      "scriptId":"u1"},
    "02a26d111d7b410b8996a8dd8e9d5fba":{
      "scriptId":"u2"},
    "c360194812c04432b0fe8d3a4bc59ffc":{
      "scriptId":"u3"},
    "f5d9d10e08fc4d2f84f957a4d6c0d05b":{
      "scriptId":"u4"},
    "ad356957b4914f1c8aaf3857aaea9801":{
      "scriptId":"u5"},
    "a006e87605394e87b5666c1c505e8597":{
      "scriptId":"u6"},
    "75e48869643946848f145b4f05cf73a2":{
      "scriptId":"u7"},
    "23912209450e4dbbb2dca0135ebdc244":{
      "scriptId":"u8"},
    "74a92c7bf5494f84b72eaf9b01c7bee6":{
      "scriptId":"u9"},
    "8fc5ff3ae11a4c8ab338de8131123667":{
      "scriptId":"u10"},
    "7d018832e2f548299affbbe856ed8d6b":{
      "scriptId":"u11"},
    "374c6e90bf374a1faa4b0d207ecd796c":{
      "scriptId":"u12"},
    "4acee0e63b0f45c2976dc5898a924af1":{
      "scriptId":"u13"},
    "375b7fd8e8c143559e1721807c960529":{
      "scriptId":"u14"},
    "3565cc6e0ec44ce48575076edf51f3c3":{
      "scriptId":"u15"},
    "cbf2b7a7153c4bf4b82e79c4b0bd432a":{
      "scriptId":"u16"},
    "ab880933b7cd46cd9cb1c10c0028bf53":{
      "scriptId":"u17"},
    "1b10c1b0be764bed9ba3a01d82307fd8":{
      "scriptId":"u18"},
    "25d314fa89d54f06a907f13423b44b06":{
      "scriptId":"u19"},
    "dc948c9c9d004f32965996a403d868ae":{
      "scriptId":"u20"},
    "55215d8c41df4755a39e57dc6793abf6":{
      "scriptId":"u21"},
    "1135e562514148789eaf83131aff7004":{
      "scriptId":"u22"},
    "a411ea16b1154fc7bd75c4a621ecd16f":{
      "scriptId":"u23"},
    "c99cc9531add425ca1638d7de627acc6":{
      "scriptId":"u24"},
    "4fff8d70cbb946b5a37554230f622953":{
      "scriptId":"u25"},
    "46361c48c22b45ca84e0559ab57aac85":{
      "scriptId":"u26"},
    "89f95ce8074e494ea8ca2b2448c47b28":{
      "scriptId":"u27"},
    "cc6ee2c36aa54085868c16aaf3f60034":{
      "scriptId":"u28"},
    "dff5fc3733e24d7d9c0f0166251a2cf3":{
      "scriptId":"u29"},
    "f58528ef17124c3f89e390fde1769049":{
      "scriptId":"u30"},
    "751632f7fc374819a6b1e640729b8f29":{
      "scriptId":"u31"},
    "8c44a594aa414883ac5ab81b94271924":{
      "scriptId":"u32"},
    "8c5c7c0ed9ff4f32a3e73fcaef6334d6":{
      "scriptId":"u33"},
    "4de15a77519a41c099a2798177f262a8":{
      "scriptId":"u34"},
    "d3458a490a8d4afa959b6d809d1aa9e4":{
      "scriptId":"u35"},
    "d246f10d0f3546358dd3fa9edfce863d":{
      "scriptId":"u36"},
    "fe636960f63042e39af79e11c286fccf":{
      "scriptId":"u37"},
    "e0ce4ca01073496ea9ccf75d7a23ff92":{
      "scriptId":"u38"},
    "1996307f27034fa2a7ef2831cd05f11e":{
      "scriptId":"u39"},
    "5763d4abc0b444eb8bb3a62dac0633e2":{
      "scriptId":"u40"},
    "457b2651f47e4b249a75be68e55e9412":{
      "scriptId":"u41"},
    "e013c08af5114123858883f6255e003b":{
      "scriptId":"u42"},
    "4f022e5f41bf4212a3be16129c6b9da2":{
      "scriptId":"u43"},
    "578a934fb91a48508782d384c1b6f172":{
      "scriptId":"u44"},
    "d1e993d6434a4d9dbff970c47fe24ebc":{
      "scriptId":"u45"},
    "694226f3f84e4189aa2cd389fb433c5d":{
      "scriptId":"u46"},
    "698e7761347947edb55a8839c5c613d4":{
      "scriptId":"u47"},
    "d7fbcb5e02874fb4896710cc6286c84a":{
      "scriptId":"u48"},
    "6324e0a6c58748f299bfd128b4dee844":{
      "scriptId":"u49"},
    "c59bfc5096bb404c97fdae47b28d7105":{
      "scriptId":"u50"},
    "98bdf73fe9f942be9008019d55f89d36":{
      "scriptId":"u51"},
    "080b87c1f5fb483e95514c7c56dd12ab":{
      "scriptId":"u52"},
    "56dfa8cabf20405daa7397196981d2af":{
      "scriptId":"u53"}}});