$axure.loadCurrentPage({
  "url":"执行结果.html",
  "generationDate":new Date(1453298203259.11),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e123d789f4ea4e3b81107b6be8416a7a",
    "type":"Axure:Page",
    "name":"执行结果",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ceda5df1d6824c2aa845c2466a8ed261",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":110},
            "size":{
              "width":300,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"031cfd456e9844128d769aa082ec3d33",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4f6ba34060fd46798688ad0a02e2957f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目详细页面/u35.png"}},
{
              "id":"cc767b54369c40d2a581212593f9be3b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7397a3ad3a6748d6aa66501927059aeb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目详细页面/u35.png"}},
{
              "id":"00db025529494434ab406ae84603197b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"15ca7fc5f5e1428a9ef150dad2de0c99",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目详细页面/u47.png"}},
{
              "id":"5e7ccefd38de45598abec975586d3588",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c907a48e28804e088d13d91d3e9f630d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目详细页面/u35.png"}},
{
              "id":"522d9d8363854382b64d64ba57dc3451",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c075b48fec3e4fe1933d09d9c25cfa8b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目详细页面/u35.png"}},
{
              "id":"ffbe320746694edd9ccb602083f4e21d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3fc66a4deaaf4648b2b85b6a4a4146e5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目详细页面/u47.png"}},
{
              "id":"f39e7fa972fd4e6cb246cb4d0dfa0b4b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1ebf73ba49a149e2bb92613f7673d987",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目详细页面/u39.png"}},
{
              "id":"9b6f4e7fd18140dbaaefbe7287e583c0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"71909f3f1ca3437dbab66d9bfa86abc5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目详细页面/u39.png"}},
{
              "id":"65fce940754e4ee8982a5314588ef0be",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4abab8f00d4b420b98ee8c5c066930a5",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目详细页面/u51.png"}}]},
{
          "id":"91f33ae2b1b746069604a8096ac782d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":110,
              "y":54},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39acf980f9044506bf19bbec70774925",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":110,
                  "y":54},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "ceda5df1d6824c2aa845c2466a8ed261":{
      "scriptId":"u0"},
    "031cfd456e9844128d769aa082ec3d33":{
      "scriptId":"u1"},
    "4f6ba34060fd46798688ad0a02e2957f":{
      "scriptId":"u2"},
    "5e7ccefd38de45598abec975586d3588":{
      "scriptId":"u3"},
    "c907a48e28804e088d13d91d3e9f630d":{
      "scriptId":"u4"},
    "f39e7fa972fd4e6cb246cb4d0dfa0b4b":{
      "scriptId":"u5"},
    "1ebf73ba49a149e2bb92613f7673d987":{
      "scriptId":"u6"},
    "cc767b54369c40d2a581212593f9be3b":{
      "scriptId":"u7"},
    "7397a3ad3a6748d6aa66501927059aeb":{
      "scriptId":"u8"},
    "522d9d8363854382b64d64ba57dc3451":{
      "scriptId":"u9"},
    "c075b48fec3e4fe1933d09d9c25cfa8b":{
      "scriptId":"u10"},
    "9b6f4e7fd18140dbaaefbe7287e583c0":{
      "scriptId":"u11"},
    "71909f3f1ca3437dbab66d9bfa86abc5":{
      "scriptId":"u12"},
    "00db025529494434ab406ae84603197b":{
      "scriptId":"u13"},
    "15ca7fc5f5e1428a9ef150dad2de0c99":{
      "scriptId":"u14"},
    "ffbe320746694edd9ccb602083f4e21d":{
      "scriptId":"u15"},
    "3fc66a4deaaf4648b2b85b6a4a4146e5":{
      "scriptId":"u16"},
    "65fce940754e4ee8982a5314588ef0be":{
      "scriptId":"u17"},
    "4abab8f00d4b420b98ee8c5c066930a5":{
      "scriptId":"u18"},
    "91f33ae2b1b746069604a8096ac782d2":{
      "scriptId":"u19"},
    "39acf980f9044506bf19bbec70774925":{
      "scriptId":"u20"}}});