$axure.loadCurrentPage({
  "url":"选择用户.html",
  "generationDate":new Date(1453298203237.11),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"461b349b34fa4709a4fe5348d8a15904",
    "type":"Axure:Page",
    "name":"选择用户",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"45ab65181cfa40c28327494e7f82690e",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":125},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"5e12da5c33ef475ab2b92c6aa727ac59",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":98,
              "y":125},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd2a3eeee2154427a49bd1678ceaf0c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":98,
                  "y":125},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a170baf6517a4d49a4fa4e1cfca35ba3",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":450,
              "y":125},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"64360b2a0893488f8806b3dcdfabdac2",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":210},
            "size":{
              "width":440,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2693a566813407382dc961d546a19bb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":147,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"63197477c541461b931f0ed5324e088f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":147,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选择用户/u5.png"}},
{
              "id":"2822973e7c9e4ec2a84cca7e40696a83",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":147,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2dcc4a50299f425697ced269bba594c0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":147,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选择用户/u5.png"}},
{
              "id":"cd2404738b1e4ac4984cfdd8645a7f31",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":147,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"54e98544c8d7458da9490c35783d9706",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":147,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选择用户/u17.png"}},
{
              "id":"cba15d043e204d378761a8ca113d6fe6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":147,
                  "y":0},
                "size":{
                  "width":147,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4fd2af3174e344b990f9645def753688",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":147,
                      "y":0},
                    "size":{
                      "width":147,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选择用户/u5.png"}},
{
              "id":"f3c4addced67446fb48f624ba69e6371",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":147,
                  "y":30},
                "size":{
                  "width":147,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"aeaaa667e80a453e8e33389136806b87",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":147,
                      "y":30},
                    "size":{
                      "width":147,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选择用户/u5.png"}},
{
              "id":"4525184b4cc9448991ae30b4f96a8160",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":147,
                  "y":60},
                "size":{
                  "width":147,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1a6a6688535749fba6a5f4cb509fccce",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":147,
                      "y":60},
                    "size":{
                      "width":147,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选择用户/u17.png"}},
{
              "id":"a8e8ec32d33246b4a3ab73970db9ee3f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":294,
                  "y":0},
                "size":{
                  "width":146,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"94db128ed7d54cbe9f84284a18188251",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":294,
                      "y":0},
                    "size":{
                      "width":146,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选择用户/u9.png"}},
{
              "id":"d76f691f23314da485c6e287614b9ce7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":294,
                  "y":30},
                "size":{
                  "width":146,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"afade6e94a7349b8b712bab55f38e791",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":294,
                      "y":30},
                    "size":{
                      "width":146,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选择用户/u9.png"}},
{
              "id":"b87e4aea8d74405788ec4dbb29b17309",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":294,
                  "y":60},
                "size":{
                  "width":146,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e6c3d0d82cf949b08862426c498894da",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":294,
                      "y":60},
                    "size":{
                      "width":146,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/选择用户/u21.png"}}]},
{
          "id":"b551804952ce4d24ac5f99fc51c3ff01",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":435,
              "y":345},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"closeCurrent",
                      "description":"关闭当前窗口"}]}]}},
          "tabbable":true},
{
          "id":"ba875a3e6b1349d982704f2cb91de0a7",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":315,
              "y":345},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"closeCurrent",
                      "description":"关闭当前窗口"}]}]}},
          "tabbable":true},
{
          "id":"3a4611e7723546bebb95d4a02ffd3dfb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":98,
              "y":44},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4eae00ccdfa41a1be7f54eea32efa34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":98,
                  "y":44},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "45ab65181cfa40c28327494e7f82690e":{
      "scriptId":"u0"},
    "5e12da5c33ef475ab2b92c6aa727ac59":{
      "scriptId":"u1"},
    "cd2a3eeee2154427a49bd1678ceaf0c4":{
      "scriptId":"u2"},
    "a170baf6517a4d49a4fa4e1cfca35ba3":{
      "scriptId":"u3"},
    "64360b2a0893488f8806b3dcdfabdac2":{
      "scriptId":"u4"},
    "f2693a566813407382dc961d546a19bb":{
      "scriptId":"u5"},
    "63197477c541461b931f0ed5324e088f":{
      "scriptId":"u6"},
    "cba15d043e204d378761a8ca113d6fe6":{
      "scriptId":"u7"},
    "4fd2af3174e344b990f9645def753688":{
      "scriptId":"u8"},
    "a8e8ec32d33246b4a3ab73970db9ee3f":{
      "scriptId":"u9"},
    "94db128ed7d54cbe9f84284a18188251":{
      "scriptId":"u10"},
    "2822973e7c9e4ec2a84cca7e40696a83":{
      "scriptId":"u11"},
    "2dcc4a50299f425697ced269bba594c0":{
      "scriptId":"u12"},
    "f3c4addced67446fb48f624ba69e6371":{
      "scriptId":"u13"},
    "aeaaa667e80a453e8e33389136806b87":{
      "scriptId":"u14"},
    "d76f691f23314da485c6e287614b9ce7":{
      "scriptId":"u15"},
    "afade6e94a7349b8b712bab55f38e791":{
      "scriptId":"u16"},
    "cd2404738b1e4ac4984cfdd8645a7f31":{
      "scriptId":"u17"},
    "54e98544c8d7458da9490c35783d9706":{
      "scriptId":"u18"},
    "4525184b4cc9448991ae30b4f96a8160":{
      "scriptId":"u19"},
    "1a6a6688535749fba6a5f4cb509fccce":{
      "scriptId":"u20"},
    "b87e4aea8d74405788ec4dbb29b17309":{
      "scriptId":"u21"},
    "e6c3d0d82cf949b08862426c498894da":{
      "scriptId":"u22"},
    "b551804952ce4d24ac5f99fc51c3ff01":{
      "scriptId":"u23"},
    "ba875a3e6b1349d982704f2cb91de0a7":{
      "scriptId":"u24"},
    "3a4611e7723546bebb95d4a02ffd3dfb":{
      "scriptId":"u25"},
    "e4eae00ccdfa41a1be7f54eea32efa34":{
      "scriptId":"u26"}}});