$axure.loadCurrentPage({
  "url":"负责人项目列表.html",
  "generationDate":new Date(1453298202972.09),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f96cab3dfaff44249e596636a0e1d0dd",
    "type":"Axure:Page",
    "name":"负责人项目列表",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b320df77f24442c390d8bba1231e9866",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":120},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f30caf43269248aab9fbbd823e1f3975",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":120},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d46805fc396646b49bea3e4f8dd7dff2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":540,
              "y":120},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5301cc7c96bb4036a49af96acddb6c1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":540,
                  "y":120},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d3c1ed38300f4bde900507616b063620",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":120},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"1697a61251ed42bea48e67e436491297",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":610,
              "y":115.5},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"529813c832a64d8aadf8f2b3626b8974",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":870,
              "y":170},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"014f4bfa5539455a9dad0ca6e815148b",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":240},
            "size":{
              "width":790,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0412fab67b534d6f850911852f68e989",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":158,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"88cd211d61084809bb1419a23d2085c1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":158,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务主任项目列表/u8.png"}},
{
              "id":"dc05422595114c4795adb67f552a3b00",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":158,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ea7ee03b064e45709178249989c3f04f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":158,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "interactionMap":{
                "onClick":{
                  "description":"OnClick",
                  "cases":[{
                      "description":"用例 1",
                      "isNewIfGroup":false,
                      "actions":[{
                          "action":"linkWindow",
                          "description":"在 新窗口/标签页 打开 项目详细页面",
                          "target":{
                            "targetType":"page",
                            "url":"项目详细页面.html",
                            "includeVariables":true},
                          "linkType":"new"}]}]}},
              "tabbable":true,
              "images":{
                "normal~":"images/业务主任项目列表/u8.png"}},
{
              "id":"7d625ce2695542d29edc6540b0f5a75b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":158,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"770f062627b44156a63d1c522dd3d7e0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":158,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务主任项目列表/u28.png"}},
{
              "id":"69de88397cf543a687c49a2cbc3a21f0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":158,
                  "y":0},
                "size":{
                  "width":158,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dc495bbb279241508a6616e1fe305ee0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":158,
                      "y":0},
                    "size":{
                      "width":158,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务主任项目列表/u8.png"}},
{
              "id":"1e8e5f42265f418a937617add44a5ea3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":158,
                  "y":30},
                "size":{
                  "width":158,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"18d649f8c35c4a7a94380c4a3517b25d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":158,
                      "y":30},
                    "size":{
                      "width":158,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务主任项目列表/u8.png"}},
{
              "id":"00e0c70e51ef448ca3fabf41b04571ee",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":158,
                  "y":60},
                "size":{
                  "width":158,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f4cc3173caf545d1b873d1897035e54c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":158,
                      "y":60},
                    "size":{
                      "width":158,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务主任项目列表/u28.png"}},
{
              "id":"17fc0863632d4bdeb2a231857bcf4150",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":316,
                  "y":0},
                "size":{
                  "width":158,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8d5a16065ef442ba90f951b9dbf05842",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":316,
                      "y":0},
                    "size":{
                      "width":158,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务主任项目列表/u8.png"}},
{
              "id":"d48200085b8c40edb7f63dd71cca9639",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":316,
                  "y":30},
                "size":{
                  "width":158,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3d16a8219a574127a3e6f028d4a441cb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":316,
                      "y":30},
                    "size":{
                      "width":158,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务主任项目列表/u8.png"}},
{
              "id":"949a780d000c4b31a32d34f12a47fd31",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":316,
                  "y":60},
                "size":{
                  "width":158,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a84cba03b1c94880bf0268e59c20fd63",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":316,
                      "y":60},
                    "size":{
                      "width":158,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务主任项目列表/u28.png"}},
{
              "id":"81f095ed64d3429ebe6bb6ca3b5dd632",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":632,
                  "y":0},
                "size":{
                  "width":158,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"81be85821f294faa8135f87c1118aaf8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":632,
                      "y":0},
                    "size":{
                      "width":158,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务主任项目列表/u16.png"}},
{
              "id":"7906a1fbe21e4573813db2a02c3fa152",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":632,
                  "y":30},
                "size":{
                  "width":158,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c274da9441ca4e49875c5cc41c85e070",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":632,
                      "y":30},
                    "size":{
                      "width":158,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务主任项目列表/u16.png"}},
{
              "id":"e629ce293d7a49b6bf8b4fbc6a0fd499",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":632,
                  "y":60},
                "size":{
                  "width":158,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"486296901c6244b89eb40db5f17f39d8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":632,
                      "y":60},
                    "size":{
                      "width":158,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务主任项目列表/u36.png"}},
{
              "id":"29e40b21dcbc4e12b9b240431d8c982e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":474,
                  "y":0},
                "size":{
                  "width":158,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ae0c45dd5cb24d9fb686146b242b387a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":474,
                      "y":0},
                    "size":{
                      "width":158,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务主任项目列表/u8.png"}},
{
              "id":"ffef5a04b76c4088a293894ad08481b0",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":474,
                  "y":30},
                "size":{
                  "width":158,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d7eb62d2939343dea1fc3810bb6daed4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":474,
                      "y":30},
                    "size":{
                      "width":158,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务主任项目列表/u8.png"}},
{
              "id":"6745087c701d4c40a13f0ac8d0ee30f9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":474,
                  "y":60},
                "size":{
                  "width":158,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0ae9e3e29d8944d0b11d557ed5d8edcd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":474,
                      "y":60},
                    "size":{
                      "width":158,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/业务主任项目列表/u28.png"}}]},
{
          "id":"f16f6ea2f5944e9c871fa97c51738f5b",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":870,
              "y":205},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 负责人指派执行人",
                      "target":{
                        "targetType":"page",
                        "url":"负责人指派执行人.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"0881b47226d24899a3f3f218c4dc5c39",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":160,
              "y":44},
            "size":{
              "width":113,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bc561e78df44ebf8255c2317be2e510",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":160,
                  "y":44},
                "size":{
                  "width":113,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "b320df77f24442c390d8bba1231e9866":{
      "scriptId":"u0"},
    "f30caf43269248aab9fbbd823e1f3975":{
      "scriptId":"u1"},
    "d46805fc396646b49bea3e4f8dd7dff2":{
      "scriptId":"u2"},
    "5301cc7c96bb4036a49af96acddb6c1b":{
      "scriptId":"u3"},
    "d3c1ed38300f4bde900507616b063620":{
      "scriptId":"u4"},
    "1697a61251ed42bea48e67e436491297":{
      "scriptId":"u5"},
    "529813c832a64d8aadf8f2b3626b8974":{
      "scriptId":"u6"},
    "014f4bfa5539455a9dad0ca6e815148b":{
      "scriptId":"u7"},
    "0412fab67b534d6f850911852f68e989":{
      "scriptId":"u8"},
    "88cd211d61084809bb1419a23d2085c1":{
      "scriptId":"u9"},
    "69de88397cf543a687c49a2cbc3a21f0":{
      "scriptId":"u10"},
    "dc495bbb279241508a6616e1fe305ee0":{
      "scriptId":"u11"},
    "17fc0863632d4bdeb2a231857bcf4150":{
      "scriptId":"u12"},
    "8d5a16065ef442ba90f951b9dbf05842":{
      "scriptId":"u13"},
    "29e40b21dcbc4e12b9b240431d8c982e":{
      "scriptId":"u14"},
    "ae0c45dd5cb24d9fb686146b242b387a":{
      "scriptId":"u15"},
    "81f095ed64d3429ebe6bb6ca3b5dd632":{
      "scriptId":"u16"},
    "81be85821f294faa8135f87c1118aaf8":{
      "scriptId":"u17"},
    "dc05422595114c4795adb67f552a3b00":{
      "scriptId":"u18"},
    "ea7ee03b064e45709178249989c3f04f":{
      "scriptId":"u19"},
    "1e8e5f42265f418a937617add44a5ea3":{
      "scriptId":"u20"},
    "18d649f8c35c4a7a94380c4a3517b25d":{
      "scriptId":"u21"},
    "d48200085b8c40edb7f63dd71cca9639":{
      "scriptId":"u22"},
    "3d16a8219a574127a3e6f028d4a441cb":{
      "scriptId":"u23"},
    "ffef5a04b76c4088a293894ad08481b0":{
      "scriptId":"u24"},
    "d7eb62d2939343dea1fc3810bb6daed4":{
      "scriptId":"u25"},
    "7906a1fbe21e4573813db2a02c3fa152":{
      "scriptId":"u26"},
    "c274da9441ca4e49875c5cc41c85e070":{
      "scriptId":"u27"},
    "7d625ce2695542d29edc6540b0f5a75b":{
      "scriptId":"u28"},
    "770f062627b44156a63d1c522dd3d7e0":{
      "scriptId":"u29"},
    "00e0c70e51ef448ca3fabf41b04571ee":{
      "scriptId":"u30"},
    "f4cc3173caf545d1b873d1897035e54c":{
      "scriptId":"u31"},
    "949a780d000c4b31a32d34f12a47fd31":{
      "scriptId":"u32"},
    "a84cba03b1c94880bf0268e59c20fd63":{
      "scriptId":"u33"},
    "6745087c701d4c40a13f0ac8d0ee30f9":{
      "scriptId":"u34"},
    "0ae9e3e29d8944d0b11d557ed5d8edcd":{
      "scriptId":"u35"},
    "e629ce293d7a49b6bf8b4fbc6a0fd499":{
      "scriptId":"u36"},
    "486296901c6244b89eb40db5f17f39d8":{
      "scriptId":"u37"},
    "f16f6ea2f5944e9c871fa97c51738f5b":{
      "scriptId":"u38"},
    "0881b47226d24899a3f3f218c4dc5c39":{
      "scriptId":"u39"},
    "4bc561e78df44ebf8255c2317be2e510":{
      "scriptId":"u40"}}});