$axure.loadCurrentPage({
  "url":"审核人审核.html",
  "generationDate":new Date(1453298203094.1),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"55f3d139705f49b2a548dc8a713d3864",
    "type":"Axure:Page",
    "name":"审核人审核",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c811433013d04693aeeb7ade52d305f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":193,
              "y":134},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eeb745c880ac465aaaa753524bd78789",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":193,
                  "y":134},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4831ca66201643eeacabe394d0d734bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":193,
              "y":183},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec94087d554f45b58017be02f620db37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":193,
                  "y":183},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4a0d154e58c648589629dd3c23e77236",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":613,
              "y":183},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a218ed288094486a8cc017da7a24ad8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":613,
                  "y":183},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"94848223e534465a8ddcba64bc0d8c77",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":185,
              "y":273},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ae334788d8e44a2bdc91416593182d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":185,
                  "y":273},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ffc8c606141f42ee840a156190556514",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":284,
              "y":134},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79f2c774f958448c8ed124cb5b11b76b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":284,
                  "y":134},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"80d94bcc2c3b4bfdbe0950554a8c1b52",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":281,
              "y":183},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5892598e05e24f7cb4ee5143dfc5f7a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":281,
                  "y":183},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b29e24889ee84953b46f88520b4dc32e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":700,
              "y":183},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"439c0cb805944d77a638effd51d4550a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":700,
                  "y":183},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0d9554d14a834ce5a4a93a39ad122cf8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":273},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5299f33c8d9041f4af11bac4b05d0a7e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":273},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"efadb254939b403b8a5ec0887b659a48",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":192,
              "y":227},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a479e0bbc1a84477b7a0443a6b247e7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":192,
                  "y":227},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e3d82125d0c64ac48eb328b7272b8330",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":277,
              "y":227},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c62eaa780d7c491fab3d30a60be1715c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":277,
                  "y":227},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1a47db75aef64a269e70d8a909adbeb4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":194,
              "y":307},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c35371dd44c149e786e34a4102730cbb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":194,
                  "y":307},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"30c0f42286fb4584947ec5ddc48ef100",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":279,
              "y":307},
            "size":{
              "width":47,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0210e2dd315454181ce6dd7a2e0f6c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":279,
                  "y":307},
                "size":{
                  "width":47,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e429025b68874344a80fcf488a84ce68",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":198,
              "y":344},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5653bbc0a63a4f4f847f82f6a2fd9ea1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":198,
                  "y":344},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"069e4ccbd9ef425a988050beb425cf22",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":283,
              "y":344},
            "size":{
              "width":47,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"177650ba78614a6a9729c40164255c42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":283,
                  "y":344},
                "size":{
                  "width":47,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"73dc5c869bcf4aff982b324fc74b9a6c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":193,
              "y":384},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b339ea50839f448486dc4411f41cfa7d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":193,
                  "y":384},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c429963e61a641149ce4acafe1db18ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":278,
              "y":384},
            "size":{
              "width":47,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ec4280c39b54df8bdb0dd79cd8025ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":278,
                  "y":384},
                "size":{
                  "width":47,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a483cd504c3f4057bbea85b862964c52",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":193,
              "y":430},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b0ce9ab635a49779f87b918ec6232ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":193,
                  "y":430},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f22d810d91f647819a75b3f1045ce842",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":193,
              "y":470},
            "size":{
              "width":300,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d3229ad3a194dbd9b82d07dff6ba645",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1fd5e1ed83d84f9d999220a741998ead",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目详细页面/u35.png"}},
{
              "id":"b8ddf26ed143401d8d15fe1b841e7dc8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"beec2461baae4b3aa039e30bf4610b52",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目详细页面/u35.png"}},
{
              "id":"8b6b7c89c39f497885d5c84152079216",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b4c57e99bc45447988e0b9f4c91400dd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目详细页面/u47.png"}},
{
              "id":"bebe938f9e454dd492fdf878c2e1efee",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e1682b6521394f7593185ff6925563b7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目详细页面/u35.png"}},
{
              "id":"d661daa1911642c1b908e378625924ea",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ad33c090b2ee4e22b72603dc1e9ea284",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目详细页面/u35.png"}},
{
              "id":"b45ede950a9e4b689eba9e3748a4e2a3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"28c653ce57fe41c2af50e3d4fa46f686",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目详细页面/u47.png"}},
{
              "id":"b6cbe5a3d50640bea479a3a828dc044e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f83be7d267b2442dbfa46b2847c6285f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目详细页面/u39.png"}},
{
              "id":"fe20dee227a244f2ab0bf28ca0e9580d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8e3919f4aed3436da5e16707542a0377",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目详细页面/u39.png"}},
{
              "id":"c63b1a1e707f467bbcfd61dfe9c34603",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4b4148364aa9456a8d68f3ee1c6367f8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目详细页面/u51.png"}}]},
{
          "id":"47aa66b92caa435987cbfe1b24ed01b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":138,
              "y":610},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4704d3220a2242f38d6cae5d3a9b073c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":138,
                  "y":610},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"908687f973f5434dbf4d49e2398d1e6b",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":193,
              "y":600},
            "size":{
              "width":317,
              "height":100}},
          "adaptiveStyles":{
}},
{
          "id":"646774f82c734cb49ef4c60dd976fc80",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":198,
              "y":770},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"closeCurrent",
                      "description":"关闭当前窗口"}]}]}},
          "tabbable":true},
{
          "id":"bfb8f24fff0247c08bc3107321db6e98",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":770},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"closeCurrent",
                      "description":"关闭当前窗口"}]}]}},
          "tabbable":true},
{
          "id":"02ac53d1f89f458ebcc3746fb3f2ea83",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":185,
              "y":50},
            "size":{
              "width":81,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d551a408875d42caa859d7e318afeb97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":185,
                  "y":50},
                "size":{
                  "width":81,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "c811433013d04693aeeb7ade52d305f8":{
      "scriptId":"u0"},
    "eeb745c880ac465aaaa753524bd78789":{
      "scriptId":"u1"},
    "4831ca66201643eeacabe394d0d734bd":{
      "scriptId":"u2"},
    "ec94087d554f45b58017be02f620db37":{
      "scriptId":"u3"},
    "4a0d154e58c648589629dd3c23e77236":{
      "scriptId":"u4"},
    "a218ed288094486a8cc017da7a24ad8c":{
      "scriptId":"u5"},
    "94848223e534465a8ddcba64bc0d8c77":{
      "scriptId":"u6"},
    "6ae334788d8e44a2bdc91416593182d3":{
      "scriptId":"u7"},
    "ffc8c606141f42ee840a156190556514":{
      "scriptId":"u8"},
    "79f2c774f958448c8ed124cb5b11b76b":{
      "scriptId":"u9"},
    "80d94bcc2c3b4bfdbe0950554a8c1b52":{
      "scriptId":"u10"},
    "5892598e05e24f7cb4ee5143dfc5f7a8":{
      "scriptId":"u11"},
    "b29e24889ee84953b46f88520b4dc32e":{
      "scriptId":"u12"},
    "439c0cb805944d77a638effd51d4550a":{
      "scriptId":"u13"},
    "0d9554d14a834ce5a4a93a39ad122cf8":{
      "scriptId":"u14"},
    "5299f33c8d9041f4af11bac4b05d0a7e":{
      "scriptId":"u15"},
    "efadb254939b403b8a5ec0887b659a48":{
      "scriptId":"u16"},
    "a479e0bbc1a84477b7a0443a6b247e7f":{
      "scriptId":"u17"},
    "e3d82125d0c64ac48eb328b7272b8330":{
      "scriptId":"u18"},
    "c62eaa780d7c491fab3d30a60be1715c":{
      "scriptId":"u19"},
    "1a47db75aef64a269e70d8a909adbeb4":{
      "scriptId":"u20"},
    "c35371dd44c149e786e34a4102730cbb":{
      "scriptId":"u21"},
    "30c0f42286fb4584947ec5ddc48ef100":{
      "scriptId":"u22"},
    "b0210e2dd315454181ce6dd7a2e0f6c6":{
      "scriptId":"u23"},
    "e429025b68874344a80fcf488a84ce68":{
      "scriptId":"u24"},
    "5653bbc0a63a4f4f847f82f6a2fd9ea1":{
      "scriptId":"u25"},
    "069e4ccbd9ef425a988050beb425cf22":{
      "scriptId":"u26"},
    "177650ba78614a6a9729c40164255c42":{
      "scriptId":"u27"},
    "73dc5c869bcf4aff982b324fc74b9a6c":{
      "scriptId":"u28"},
    "b339ea50839f448486dc4411f41cfa7d":{
      "scriptId":"u29"},
    "c429963e61a641149ce4acafe1db18ca":{
      "scriptId":"u30"},
    "6ec4280c39b54df8bdb0dd79cd8025ca":{
      "scriptId":"u31"},
    "a483cd504c3f4057bbea85b862964c52":{
      "scriptId":"u32"},
    "1b0ce9ab635a49779f87b918ec6232ef":{
      "scriptId":"u33"},
    "f22d810d91f647819a75b3f1045ce842":{
      "scriptId":"u34"},
    "1d3229ad3a194dbd9b82d07dff6ba645":{
      "scriptId":"u35"},
    "1fd5e1ed83d84f9d999220a741998ead":{
      "scriptId":"u36"},
    "bebe938f9e454dd492fdf878c2e1efee":{
      "scriptId":"u37"},
    "e1682b6521394f7593185ff6925563b7":{
      "scriptId":"u38"},
    "b6cbe5a3d50640bea479a3a828dc044e":{
      "scriptId":"u39"},
    "f83be7d267b2442dbfa46b2847c6285f":{
      "scriptId":"u40"},
    "b8ddf26ed143401d8d15fe1b841e7dc8":{
      "scriptId":"u41"},
    "beec2461baae4b3aa039e30bf4610b52":{
      "scriptId":"u42"},
    "d661daa1911642c1b908e378625924ea":{
      "scriptId":"u43"},
    "ad33c090b2ee4e22b72603dc1e9ea284":{
      "scriptId":"u44"},
    "fe20dee227a244f2ab0bf28ca0e9580d":{
      "scriptId":"u45"},
    "8e3919f4aed3436da5e16707542a0377":{
      "scriptId":"u46"},
    "8b6b7c89c39f497885d5c84152079216":{
      "scriptId":"u47"},
    "b4c57e99bc45447988e0b9f4c91400dd":{
      "scriptId":"u48"},
    "b45ede950a9e4b689eba9e3748a4e2a3":{
      "scriptId":"u49"},
    "28c653ce57fe41c2af50e3d4fa46f686":{
      "scriptId":"u50"},
    "c63b1a1e707f467bbcfd61dfe9c34603":{
      "scriptId":"u51"},
    "4b4148364aa9456a8d68f3ee1c6367f8":{
      "scriptId":"u52"},
    "47aa66b92caa435987cbfe1b24ed01b9":{
      "scriptId":"u53"},
    "4704d3220a2242f38d6cae5d3a9b073c":{
      "scriptId":"u54"},
    "908687f973f5434dbf4d49e2398d1e6b":{
      "scriptId":"u55"},
    "646774f82c734cb49ef4c60dd976fc80":{
      "scriptId":"u56"},
    "bfb8f24fff0247c08bc3107321db6e98":{
      "scriptId":"u57"},
    "02ac53d1f89f458ebcc3746fb3f2ea83":{
      "scriptId":"u58"},
    "d551a408875d42caa859d7e318afeb97":{
      "scriptId":"u59"}}});