$axure.loadCurrentPage({
  "url":"确定人确定.html",
  "generationDate":new Date(1453298469560.97),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0eccc22a8103408c85f07459e622bf96",
    "type":"Axure:Page",
    "name":"确定人确定",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"24bb7b3364ab4d11b25a7437a54f0139",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":193,
              "y":134},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3fce892b6f543b8b24750b093a82da7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":193,
                  "y":134},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1a03e1984dda447ea8530e599e599905",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":193,
              "y":183},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb4b9854ceec42aa938489a7aa4d1ca2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":193,
                  "y":183},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f1c4ab4c93f244628541c12098e58213",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":613,
              "y":183},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d85c82649d5746849c2d4bb2e6f200aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":613,
                  "y":183},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cc3d05de95e74711b121ab217b3e0d56",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":185,
              "y":273},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5cdd86b476f841cb8db475635030a7c1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":185,
                  "y":273},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c212a3bd696943e381ce19a7aed70e67",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":284,
              "y":134},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dbb38cbf63fc429f95c677907a5d30d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":284,
                  "y":134},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3b72669777bf4dcf9092350fecb4a292",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":281,
              "y":183},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc650e2d8a324aa086374f19610a5ec3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":281,
                  "y":183},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"16691dca463d481f93eefc2253832c44",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":700,
              "y":183},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f26f9dbd3e694061b0d026eac7336504",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":700,
                  "y":183},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e5c02d66e4d1439bbed2fc1bd7f63537",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":273},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e136efb46914f8a854c21537ab6f379",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":273},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fb1292f01825481fac24303dc4f88372",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":192,
              "y":227},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eac1eec4b2834ac997e7ba718c935a5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":192,
                  "y":227},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"08891d420745428cb039340068c76c1e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":277,
              "y":227},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"496817c81a1f4f46b1387775d7f42f4b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":277,
                  "y":227},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7c7f0ab90c4d45f7818cc26a9cf0e581",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":194,
              "y":307},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e42d3a3723d64df99d90a783212aacaa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":194,
                  "y":307},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"65318944e17d48e9bfde6c57ca17a3c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":279,
              "y":307},
            "size":{
              "width":47,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94b01220b99842b884537615941cf415",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":279,
                  "y":307},
                "size":{
                  "width":47,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9c1ee6b0e6f14d92863114f438642f72",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":198,
              "y":344},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"184d931385304834ad21aaa929b3c29e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":198,
                  "y":344},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"78054289e53b406c84368a90e9f03c07",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":283,
              "y":344},
            "size":{
              "width":47,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c57dbe1a40b04820be9c18da41a3b9eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":283,
                  "y":344},
                "size":{
                  "width":47,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5900acbe94a2415f9eea9d04a5952a4f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":193,
              "y":384},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d87bd240cb764b94842e40de510deec2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":193,
                  "y":384},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7ca041e9549145ab85de8018f371639f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":278,
              "y":384},
            "size":{
              "width":47,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b89f394173c491a9c3996f6d5bde9f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":278,
                  "y":384},
                "size":{
                  "width":47,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"94ad31881f3a4cf69a1dd86de4448d2c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":193,
              "y":430},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"149b3bc4f0234c5288567847dd837607",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":193,
                  "y":430},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"879d0a5113eb475394cea70086d85466",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":193,
              "y":470},
            "size":{
              "width":300,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"232fafdd10484736883c594d71522140",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6dfe0e246dbf430495a9b7d359a6bc3f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目详细页面/u35.png"}},
{
              "id":"1ce7139765694f509fec2ae7ecbc5a4a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7475d26f200746ebaa858dc68e298ab2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目详细页面/u35.png"}},
{
              "id":"10b447582c2a42d5b8490d6f8d788e17",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d7a2922e8f2b4ef1a3e06b9f5e8cc4bb",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目详细页面/u47.png"}},
{
              "id":"9a2c1d013c01438cad712293830f11e9",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"23ed2ceff77f45a6b1f650f93e40d777",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目详细页面/u35.png"}},
{
              "id":"7d01b8da3e8443b1ad11a40c2c28575b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ba2b6e0428b94f9584469fe116422c95",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目详细页面/u35.png"}},
{
              "id":"5062bc4de8c94c8d9bae4eab055671ed",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"80bdf328456a420da4a4591ab0dcbe6c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目详细页面/u47.png"}},
{
              "id":"3dd3c468cf5644a49f066960aaecd28b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"917a0ef22a6b4514a365f07e38d6f161",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目详细页面/u39.png"}},
{
              "id":"bdc6dcfcff7a494db8d3154fc02794f4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3f558942a9924fe4a6bd35a610c8bf7c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目详细页面/u39.png"}},
{
              "id":"6d68272b04544717b495d5eaa67e7ef5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ef7776c45bbc41ae8a61db2c8c38053e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/项目详细页面/u51.png"}}]},
{
          "id":"4cfc7e4ee819419e8cc95b39b672a2ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":138,
              "y":610},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc5d1070b04d4821bc4b5cad10625e9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":138,
                  "y":610},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"da9f33d3853145a9a87b6c9329ebe7d0",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":193,
              "y":600},
            "size":{
              "width":317,
              "height":100}},
          "adaptiveStyles":{
}},
{
          "id":"b6b7fd6da65d4fb2957cc3e2ef9fc1ad",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":198,
              "y":770},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"closeCurrent",
                      "description":"关闭当前窗口"}]}]}},
          "tabbable":true},
{
          "id":"2a07606d45464cd4944b4cd5ac8e4467",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":128,
              "y":40},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e53c58a79294381a56d9e4ce51d160b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":128,
                  "y":40},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "24bb7b3364ab4d11b25a7437a54f0139":{
      "scriptId":"u0"},
    "f3fce892b6f543b8b24750b093a82da7":{
      "scriptId":"u1"},
    "1a03e1984dda447ea8530e599e599905":{
      "scriptId":"u2"},
    "fb4b9854ceec42aa938489a7aa4d1ca2":{
      "scriptId":"u3"},
    "f1c4ab4c93f244628541c12098e58213":{
      "scriptId":"u4"},
    "d85c82649d5746849c2d4bb2e6f200aa":{
      "scriptId":"u5"},
    "cc3d05de95e74711b121ab217b3e0d56":{
      "scriptId":"u6"},
    "5cdd86b476f841cb8db475635030a7c1":{
      "scriptId":"u7"},
    "c212a3bd696943e381ce19a7aed70e67":{
      "scriptId":"u8"},
    "dbb38cbf63fc429f95c677907a5d30d5":{
      "scriptId":"u9"},
    "3b72669777bf4dcf9092350fecb4a292":{
      "scriptId":"u10"},
    "bc650e2d8a324aa086374f19610a5ec3":{
      "scriptId":"u11"},
    "16691dca463d481f93eefc2253832c44":{
      "scriptId":"u12"},
    "f26f9dbd3e694061b0d026eac7336504":{
      "scriptId":"u13"},
    "e5c02d66e4d1439bbed2fc1bd7f63537":{
      "scriptId":"u14"},
    "3e136efb46914f8a854c21537ab6f379":{
      "scriptId":"u15"},
    "fb1292f01825481fac24303dc4f88372":{
      "scriptId":"u16"},
    "eac1eec4b2834ac997e7ba718c935a5f":{
      "scriptId":"u17"},
    "08891d420745428cb039340068c76c1e":{
      "scriptId":"u18"},
    "496817c81a1f4f46b1387775d7f42f4b":{
      "scriptId":"u19"},
    "7c7f0ab90c4d45f7818cc26a9cf0e581":{
      "scriptId":"u20"},
    "e42d3a3723d64df99d90a783212aacaa":{
      "scriptId":"u21"},
    "65318944e17d48e9bfde6c57ca17a3c8":{
      "scriptId":"u22"},
    "94b01220b99842b884537615941cf415":{
      "scriptId":"u23"},
    "9c1ee6b0e6f14d92863114f438642f72":{
      "scriptId":"u24"},
    "184d931385304834ad21aaa929b3c29e":{
      "scriptId":"u25"},
    "78054289e53b406c84368a90e9f03c07":{
      "scriptId":"u26"},
    "c57dbe1a40b04820be9c18da41a3b9eb":{
      "scriptId":"u27"},
    "5900acbe94a2415f9eea9d04a5952a4f":{
      "scriptId":"u28"},
    "d87bd240cb764b94842e40de510deec2":{
      "scriptId":"u29"},
    "7ca041e9549145ab85de8018f371639f":{
      "scriptId":"u30"},
    "1b89f394173c491a9c3996f6d5bde9f1":{
      "scriptId":"u31"},
    "94ad31881f3a4cf69a1dd86de4448d2c":{
      "scriptId":"u32"},
    "149b3bc4f0234c5288567847dd837607":{
      "scriptId":"u33"},
    "879d0a5113eb475394cea70086d85466":{
      "scriptId":"u34"},
    "232fafdd10484736883c594d71522140":{
      "scriptId":"u35"},
    "6dfe0e246dbf430495a9b7d359a6bc3f":{
      "scriptId":"u36"},
    "9a2c1d013c01438cad712293830f11e9":{
      "scriptId":"u37"},
    "23ed2ceff77f45a6b1f650f93e40d777":{
      "scriptId":"u38"},
    "3dd3c468cf5644a49f066960aaecd28b":{
      "scriptId":"u39"},
    "917a0ef22a6b4514a365f07e38d6f161":{
      "scriptId":"u40"},
    "1ce7139765694f509fec2ae7ecbc5a4a":{
      "scriptId":"u41"},
    "7475d26f200746ebaa858dc68e298ab2":{
      "scriptId":"u42"},
    "7d01b8da3e8443b1ad11a40c2c28575b":{
      "scriptId":"u43"},
    "ba2b6e0428b94f9584469fe116422c95":{
      "scriptId":"u44"},
    "bdc6dcfcff7a494db8d3154fc02794f4":{
      "scriptId":"u45"},
    "3f558942a9924fe4a6bd35a610c8bf7c":{
      "scriptId":"u46"},
    "10b447582c2a42d5b8490d6f8d788e17":{
      "scriptId":"u47"},
    "d7a2922e8f2b4ef1a3e06b9f5e8cc4bb":{
      "scriptId":"u48"},
    "5062bc4de8c94c8d9bae4eab055671ed":{
      "scriptId":"u49"},
    "80bdf328456a420da4a4591ab0dcbe6c":{
      "scriptId":"u50"},
    "6d68272b04544717b495d5eaa67e7ef5":{
      "scriptId":"u51"},
    "ef7776c45bbc41ae8a61db2c8c38053e":{
      "scriptId":"u52"},
    "4cfc7e4ee819419e8cc95b39b672a2ff":{
      "scriptId":"u53"},
    "fc5d1070b04d4821bc4b5cad10625e9b":{
      "scriptId":"u54"},
    "da9f33d3853145a9a87b6c9329ebe7d0":{
      "scriptId":"u55"},
    "b6b7fd6da65d4fb2957cc3e2ef9fc1ad":{
      "scriptId":"u56"},
    "2a07606d45464cd4944b4cd5ac8e4467":{
      "scriptId":"u57"},
    "1e53c58a79294381a56d9e4ce51d160b":{
      "scriptId":"u58"}}});