$axure.loadCurrentPage({
  "url":"经营主任提交项目.html",
  "generationDate":new Date(1453298469134.94),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4b306ee128ab4cd6878f1a5ec0790a5d",
    "type":"Axure:Page",
    "name":"经营主任提交项目",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5cb73c9891a2400eb0420a73952d53e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":258,
              "y":134},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f3e8cc3637240e7a8186cc28eff2321",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":258,
                  "y":134},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9937659b87f94e3abafead3cc7581998",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":334,
              "y":134},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"ba172b5b7ab54d78b945c8943da3e35d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":180},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41eb74239ef543b2babeb0dde1305715",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":180},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d8aa2cba7ca04821a4c443058cf30d60",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":670,
              "y":180},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b179858ce2e34bb39f37a17d4935adde",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":670,
                  "y":180},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a717ee0778d748d59069091784166996",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":334,
              "y":169},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"5da40e2e2a8b4ff7a607cba8b1ad7720",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":770,
              "y":171},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"73d569481ec8436287c4e2698d919943",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":590,
              "y":315},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 经营主任项目列表",
                      "target":{
                        "targetType":"page",
                        "url":"经营主任项目列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"3caed0658d6a45a4a21beed6dba79a78",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":770,
              "y":315},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 经营主任项目列表",
                      "target":{
                        "targetType":"page",
                        "url":"经营主任项目列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"7649256eabdf41a7b90b7a8aeba85173",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":224},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36b7a87494554dbfa652281c323b4334",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":224},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"82960d0347f2487080b8973c5ed11fec",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":334,
              "y":218},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"1d4d4260050b4dbc879126de21d416a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":190,
              "y":44},
            "size":{
              "width":97,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3639d2380ce248c9bb248a4a418d4078",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":190,
                  "y":44},
                "size":{
                  "width":97,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "5cb73c9891a2400eb0420a73952d53e9":{
      "scriptId":"u0"},
    "2f3e8cc3637240e7a8186cc28eff2321":{
      "scriptId":"u1"},
    "9937659b87f94e3abafead3cc7581998":{
      "scriptId":"u2"},
    "ba172b5b7ab54d78b945c8943da3e35d":{
      "scriptId":"u3"},
    "41eb74239ef543b2babeb0dde1305715":{
      "scriptId":"u4"},
    "d8aa2cba7ca04821a4c443058cf30d60":{
      "scriptId":"u5"},
    "b179858ce2e34bb39f37a17d4935adde":{
      "scriptId":"u6"},
    "a717ee0778d748d59069091784166996":{
      "scriptId":"u7"},
    "5da40e2e2a8b4ff7a607cba8b1ad7720":{
      "scriptId":"u8"},
    "73d569481ec8436287c4e2698d919943":{
      "scriptId":"u9"},
    "3caed0658d6a45a4a21beed6dba79a78":{
      "scriptId":"u10"},
    "7649256eabdf41a7b90b7a8aeba85173":{
      "scriptId":"u11"},
    "36b7a87494554dbfa652281c323b4334":{
      "scriptId":"u12"},
    "82960d0347f2487080b8973c5ed11fec":{
      "scriptId":"u13"},
    "1d4d4260050b4dbc879126de21d416a4":{
      "scriptId":"u14"},
    "3639d2380ce248c9bb248a4a418d4078":{
      "scriptId":"u15"}}});