$axure.loadCurrentPage({
  "url":"负责人指派执行人.html",
  "generationDate":new Date(1453298202991.09),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b1e2e17feb7f4986a54e61e6ef942e84",
    "type":"Axure:Page",
    "name":"负责人指派执行人",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"bbe020613058440bbc52f07373370d24",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":178,
              "y":94},
            "size":{
              "width":52,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ece7a8a95d246b6a9612d2bff95b46d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":178,
                  "y":94},
                "size":{
                  "width":52,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4e2d4e42273a4a37b2497570851afc94",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":94},
            "size":{
              "width":47,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4d49a4835734d93b8260b4d70e1d83c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":94},
                "size":{
                  "width":47,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c6cd3f548caa4cd98704d5732b4f722a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":617,
              "y":94},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93e8bb479caf4910947270bd0273c593",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":617,
                  "y":94},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b83cbe9513284b19b5e8af59b08079c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":720,
              "y":94},
            "size":{
              "width":47,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd11e4be598b42a89b351c71baac08ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":720,
                  "y":94},
                "size":{
                  "width":47,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3f84c30c318b43c08a316a630aa197ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":164,
              "y":144},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf0b002cdacf4c478d3d4c768222a8ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":164,
                  "y":144},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0048bc78c14146e9b0c8ad23910dcdd3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":144},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8bcc11155a9145af902d9e87154b38d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":144},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"112a3550255943e8832c93b8ebf4c5eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":604,
              "y":144},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"454cbb86b73c4842894098a35a784b10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":604,
                  "y":144},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"213c2ec682c94b7ebe7ca8eb9acb7e97",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":720,
              "y":144},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d928042232424f0abd7e55c7227bc78b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":720,
                  "y":144},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7053d4db710144d49622fff1e6b68890",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":151,
              "y":214},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f8f217b3dac4dd7b76f8b3fc3cc9d52",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":151,
                  "y":214},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"aea7f9d9c3994f099fa3016a9ddd39a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":214},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90c9807fc8e84833985a4b17c0921b44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":214},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dd55afad6d0047ff98b9390c277e58c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":125,
              "y":264},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6f6b93a0cce4847b24f662d5c9e92c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":125,
                  "y":264},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5d18e05b7c4746e4958bb44e48a2bf05",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":264},
            "size":{
              "width":200,
              "height":22}},
          "adaptiveStyles":{
}},
{
          "id":"a81e193111a0407986484af0ec706649",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":610,
              "y":264},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8b0f860be634a298b3ad8f1b5684d8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":610,
                  "y":264},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"296d389422e04b75b5e521af880fa310",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":714,
              "y":264},
            "size":{
              "width":47,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"772a1825d97b45a1a607a62c38db3aa7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":714,
                  "y":264},
                "size":{
                  "width":47,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ef53d4718dd747b7ba8b41d1f0c9d93d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":820,
              "y":259.5},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 弹出窗口 打开 选择用户",
                      "target":{
                        "targetType":"page",
                        "url":"选择用户.html",
                        "includeVariables":true},
                      "linkType":"popup",
                      "popup":{
                        "left":100,
                        "top":100,
                        "width":500,
                        "height":500,
                        "toolbar":false,
                        "scrollbars":false,
                        "location":false,
                        "status":false,
                        "menubar":false,
                        "directories":false,
                        "resizable":false,
                        "centerwindow":true}}]}]}},
          "tabbable":true},
{
          "id":"c90154b6215f4a6f834b4e5b2f727f80",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":604,
              "y":214},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eff9c09a2e3f4c7bb31987cd6cadd9d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":604,
                  "y":214},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ad07dd3f888c43aca12f07ad602dbeb1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":720,
              "y":214},
            "size":{
              "width":47,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28c548d8f2984e499511d4d9e02d69d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":720,
                  "y":214},
                "size":{
                  "width":47,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b99c499a31404ffb848a63de000839ce",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":700,
              "y":375},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 负责人项目列表",
                      "target":{
                        "targetType":"page",
                        "url":"负责人项目列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"9f1868fe38024a3e99ae790d63cf873a",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":830,
              "y":375},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 负责人项目列表",
                      "target":{
                        "targetType":"page",
                        "url":"负责人项目列表.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"84f4b94bda0d4eee9f24e4a4900e6221",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":151,
              "y":40},
            "size":{
              "width":81,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3400f94155fd4355920534f0781f9d73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":151,
                  "y":40},
                "size":{
                  "width":81,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "bbe020613058440bbc52f07373370d24":{
      "scriptId":"u0"},
    "9ece7a8a95d246b6a9612d2bff95b46d":{
      "scriptId":"u1"},
    "4e2d4e42273a4a37b2497570851afc94":{
      "scriptId":"u2"},
    "c4d49a4835734d93b8260b4d70e1d83c":{
      "scriptId":"u3"},
    "c6cd3f548caa4cd98704d5732b4f722a":{
      "scriptId":"u4"},
    "93e8bb479caf4910947270bd0273c593":{
      "scriptId":"u5"},
    "b83cbe9513284b19b5e8af59b08079c2":{
      "scriptId":"u6"},
    "dd11e4be598b42a89b351c71baac08ee":{
      "scriptId":"u7"},
    "3f84c30c318b43c08a316a630aa197ed":{
      "scriptId":"u8"},
    "cf0b002cdacf4c478d3d4c768222a8ff":{
      "scriptId":"u9"},
    "0048bc78c14146e9b0c8ad23910dcdd3":{
      "scriptId":"u10"},
    "8bcc11155a9145af902d9e87154b38d9":{
      "scriptId":"u11"},
    "112a3550255943e8832c93b8ebf4c5eb":{
      "scriptId":"u12"},
    "454cbb86b73c4842894098a35a784b10":{
      "scriptId":"u13"},
    "213c2ec682c94b7ebe7ca8eb9acb7e97":{
      "scriptId":"u14"},
    "d928042232424f0abd7e55c7227bc78b":{
      "scriptId":"u15"},
    "7053d4db710144d49622fff1e6b68890":{
      "scriptId":"u16"},
    "1f8f217b3dac4dd7b76f8b3fc3cc9d52":{
      "scriptId":"u17"},
    "aea7f9d9c3994f099fa3016a9ddd39a3":{
      "scriptId":"u18"},
    "90c9807fc8e84833985a4b17c0921b44":{
      "scriptId":"u19"},
    "dd55afad6d0047ff98b9390c277e58c0":{
      "scriptId":"u20"},
    "e6f6b93a0cce4847b24f662d5c9e92c6":{
      "scriptId":"u21"},
    "5d18e05b7c4746e4958bb44e48a2bf05":{
      "scriptId":"u22"},
    "a81e193111a0407986484af0ec706649":{
      "scriptId":"u23"},
    "d8b0f860be634a298b3ad8f1b5684d8f":{
      "scriptId":"u24"},
    "296d389422e04b75b5e521af880fa310":{
      "scriptId":"u25"},
    "772a1825d97b45a1a607a62c38db3aa7":{
      "scriptId":"u26"},
    "ef53d4718dd747b7ba8b41d1f0c9d93d":{
      "scriptId":"u27"},
    "c90154b6215f4a6f834b4e5b2f727f80":{
      "scriptId":"u28"},
    "eff9c09a2e3f4c7bb31987cd6cadd9d8":{
      "scriptId":"u29"},
    "ad07dd3f888c43aca12f07ad602dbeb1":{
      "scriptId":"u30"},
    "28c548d8f2984e499511d4d9e02d69d6":{
      "scriptId":"u31"},
    "b99c499a31404ffb848a63de000839ce":{
      "scriptId":"u32"},
    "9f1868fe38024a3e99ae790d63cf873a":{
      "scriptId":"u33"},
    "84f4b94bda0d4eee9f24e4a4900e6221":{
      "scriptId":"u34"},
    "3400f94155fd4355920534f0781f9d73":{
      "scriptId":"u35"}}});