$axure.loadCurrentPage({
  "url":"确定人项目列表.html",
  "generationDate":new Date(1453298509783.27),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2f6b9a42582b4bd0aa021846282fd48d",
    "type":"Axure:Page",
    "name":"确定人项目列表",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"18cadc144fd04a238826526be345a461",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":120},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5b2359343fe4d6d9fe9e7582137386f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":120},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0f5587dd0a2a43f7b64bdc95a6c8beb4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":540,
              "y":120},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"def989e34ae945109f85f86604a846e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":540,
                  "y":120},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e84a0bd1594e4cd6a6455609a93654ae",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":120},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4f58ede0ee584039ab968789e433d536",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":610,
              "y":115.5},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f7dd76d3ef904067880c79daa6871bfa",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":960,
              "y":165},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"8a843cfbc5e74a97892bb83c731b2fab",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":168,
              "y":260},
            "size":{
              "width":1249,
              "height":87}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08148cdfb9734883890fe43404929efa",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":178,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6f95feab057e4e6b9a05b64e4b215d7c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":178,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/确定人项目列表/regen/u8.png"}},
{
              "id":"0db8235c4c0740c18ead97c02b9cccc6",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":178,
                  "height":27}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"59abf7dfbb0c420291c124016c3dd0c0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":178,
                      "height":27}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/确定人项目列表/regen/u22.png"}},
{
              "id":"5c682ebf65a94c76a0d3b8612faec67a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":57},
                "size":{
                  "width":178,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f889c70deaed4a09b93d053384bd3902",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":57},
                    "size":{
                      "width":178,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/确定人项目列表/regen/u36.png"}},
{
              "id":"6b3362dacf9843f99650e63a02db737b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":178,
                  "y":0},
                "size":{
                  "width":178,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"26e366c6f76141c69652d93460c78f93",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":178,
                      "y":0},
                    "size":{
                      "width":178,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/确定人项目列表/regen/u8.png"}},
{
              "id":"4e291fed272e436db5efd5cc59a86988",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":178,
                  "y":30},
                "size":{
                  "width":178,
                  "height":27}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"0788fa1e532b48abbdc829f773ea8a0f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":178,
                      "y":30},
                    "size":{
                      "width":178,
                      "height":27}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/确定人项目列表/regen/u22.png"}},
{
              "id":"50cf14a30ba34ab981371fb8b7e53ada",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":178,
                  "y":57},
                "size":{
                  "width":178,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"42f7d0697c59400a9adc2e9fe2223aff",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":178,
                      "y":57},
                    "size":{
                      "width":178,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/确定人项目列表/regen/u36.png"}},
{
              "id":"567a81fd2f354fe1b0abdea908562579",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":356,
                  "y":0},
                "size":{
                  "width":178,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"96f8f0933e9d47539ebc37163157499f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":356,
                      "y":0},
                    "size":{
                      "width":178,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/确定人项目列表/regen/u8.png"}},
{
              "id":"c57fa25fe0704b9ab2b4f6631a73288c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":356,
                  "y":30},
                "size":{
                  "width":178,
                  "height":27}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dd35e27c78854147a0df504b516ec91e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":356,
                      "y":30},
                    "size":{
                      "width":178,
                      "height":27}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/确定人项目列表/regen/u22.png"}},
{
              "id":"8bb36898ffbd4557aa06093c6c11f94a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":356,
                  "y":57},
                "size":{
                  "width":178,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c07c2ca677e84910aaddab4a463c553a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":356,
                      "y":57},
                    "size":{
                      "width":178,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/确定人项目列表/regen/u36.png"}},
{
              "id":"8bd035d5098644619ba39532521d1e44",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":1068,
                  "y":0},
                "size":{
                  "width":181,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8f5b4aa44c5c430ebed37f77961fc5b0",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":1068,
                      "y":0},
                    "size":{
                      "width":181,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/确定人项目列表/regen/u20.png"}},
{
              "id":"0be1d8b6c9f54b5b89e0045bd7611c2a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":1068,
                  "y":30},
                "size":{
                  "width":181,
                  "height":27}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4b91c162f72a432ebed29e7ba8345ebc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":1068,
                      "y":30},
                    "size":{
                      "width":181,
                      "height":27}},
                  "adaptiveStyles":{
}}],
              "interactionMap":{
                "onClick":{
                  "description":"OnClick",
                  "cases":[{
                      "description":"用例 1",
                      "isNewIfGroup":false,
                      "actions":[{
                          "action":"linkWindow",
                          "description":"在 弹出窗口 打开 确定人确定",
                          "target":{
                            "targetType":"page",
                            "url":"确定人确定.html",
                            "includeVariables":true},
                          "linkType":"popup",
                          "popup":{
                            "left":100,
                            "top":100,
                            "width":500,
                            "height":500,
                            "toolbar":false,
                            "scrollbars":false,
                            "location":false,
                            "status":false,
                            "menubar":false,
                            "directories":false,
                            "resizable":false,
                            "centerwindow":true}}]}]}},
              "tabbable":true,
              "images":{
                "normal~":"images/确定人项目列表/regen/u34.png"}},
{
              "id":"5aa470a58861432781961700e291c89d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":1068,
                  "y":57},
                "size":{
                  "width":181,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f8b897923c284efa86a50eeaa6ef96e6",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":1068,
                      "y":57},
                    "size":{
                      "width":181,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/确定人项目列表/regen/u48.png"}},
{
              "id":"ef8357f3f83d46a3820c55dc87ef67db",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":534,
                  "y":0},
                "size":{
                  "width":178,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"b68082fd583d44b9bcee640ec6e56ef9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":534,
                      "y":0},
                    "size":{
                      "width":178,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/确定人项目列表/regen/u8.png"}},
{
              "id":"f3ab2257012a4442b44ddb8ab60d407f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":534,
                  "y":30},
                "size":{
                  "width":178,
                  "height":27}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4a12459fb3114deea1b011582105e093",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":534,
                      "y":30},
                    "size":{
                      "width":178,
                      "height":27}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/确定人项目列表/regen/u22.png"}},
{
              "id":"c91f26a4b8f544a888921a16f2eaa03c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":534,
                  "y":57},
                "size":{
                  "width":178,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3cd4d89ea4484e3caedd41955e55db55",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":534,
                      "y":57},
                    "size":{
                      "width":178,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/确定人项目列表/regen/u36.png"}},
{
              "id":"c6cc88e661d848e5a1554c0b6a2ead59",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":712,
                  "y":0},
                "size":{
                  "width":178,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"d167eea33bd44d4696db010ebdde1898",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":712,
                      "y":0},
                    "size":{
                      "width":178,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/确定人项目列表/regen/u8.png"}},
{
              "id":"5279ea82b9af40488362c2dca92223f5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":712,
                  "y":30},
                "size":{
                  "width":178,
                  "height":27}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"15482e478480446e8b3ae8b58766b9e3",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":712,
                      "y":30},
                    "size":{
                      "width":178,
                      "height":27}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/确定人项目列表/regen/u22.png"}},
{
              "id":"bd4f65c1c11243e1904b52c642e2229f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":712,
                  "y":57},
                "size":{
                  "width":178,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"52456c50c94a470ca75b3bc83a643935",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":712,
                      "y":57},
                    "size":{
                      "width":178,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/确定人项目列表/regen/u36.png"}},
{
              "id":"5a4da6d487ce41e4bf8147d535012473",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":890,
                  "y":0},
                "size":{
                  "width":178,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e264d493531e4eb59886bdc8a8f220bd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":890,
                      "y":0},
                    "size":{
                      "width":178,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/确定人项目列表/regen/u8.png"}},
{
              "id":"efafcbcfb10a47e88147b67f06c68da5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":890,
                  "y":30},
                "size":{
                  "width":178,
                  "height":27}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"faa04e5bf32c400c9188406dabb624bc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":890,
                      "y":30},
                    "size":{
                      "width":178,
                      "height":27}},
                  "adaptiveStyles":{
}}],
              "interactionMap":{
                "onClick":{
                  "description":"OnClick",
                  "cases":[{
                      "description":"用例 1",
                      "isNewIfGroup":false,
                      "actions":[{
                          "action":"linkWindow",
                          "description":"在 弹出窗口 打开 执行结果",
                          "target":{
                            "targetType":"page",
                            "url":"执行结果.html",
                            "includeVariables":true},
                          "linkType":"popup",
                          "popup":{
                            "left":100,
                            "top":100,
                            "width":500,
                            "height":500,
                            "toolbar":false,
                            "scrollbars":false,
                            "location":false,
                            "status":false,
                            "menubar":false,
                            "directories":false,
                            "resizable":false,
                            "centerwindow":true}}]}]}},
              "tabbable":true,
              "images":{
                "normal~":"images/确定人项目列表/regen/u22.png"}},
{
              "id":"5aade02f10d14050959f3f1da88d855b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":890,
                  "y":57},
                "size":{
                  "width":178,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"484ba5786ce34349b200ecdf3324cfe4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":890,
                      "y":57},
                    "size":{
                      "width":178,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/确定人项目列表/regen/u36.png"}}]},
{
          "id":"789f2f4d5169440081e64d795795eb3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":238,
              "y":297},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45ed29b505304a4d9ea0746ffdda06d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":238,
                  "y":297},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 项目详细页面",
                      "target":{
                        "targetType":"page",
                        "url":"项目详细页面.html",
                        "includeVariables":true},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7722802fa5704f9d81f56dcc8b49bfa5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":138,
              "y":44},
            "size":{
              "width":113,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c699c9ea18d425dbea838c956cae877",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"700",
                "location":{
                  "x":138,
                  "y":44},
                "size":{
                  "width":113,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "18cadc144fd04a238826526be345a461":{
      "scriptId":"u0"},
    "d5b2359343fe4d6d9fe9e7582137386f":{
      "scriptId":"u1"},
    "0f5587dd0a2a43f7b64bdc95a6c8beb4":{
      "scriptId":"u2"},
    "def989e34ae945109f85f86604a846e9":{
      "scriptId":"u3"},
    "e84a0bd1594e4cd6a6455609a93654ae":{
      "scriptId":"u4"},
    "4f58ede0ee584039ab968789e433d536":{
      "scriptId":"u5"},
    "f7dd76d3ef904067880c79daa6871bfa":{
      "scriptId":"u6"},
    "8a843cfbc5e74a97892bb83c731b2fab":{
      "scriptId":"u7"},
    "08148cdfb9734883890fe43404929efa":{
      "scriptId":"u8"},
    "6f95feab057e4e6b9a05b64e4b215d7c":{
      "scriptId":"u9"},
    "6b3362dacf9843f99650e63a02db737b":{
      "scriptId":"u10"},
    "26e366c6f76141c69652d93460c78f93":{
      "scriptId":"u11"},
    "567a81fd2f354fe1b0abdea908562579":{
      "scriptId":"u12"},
    "96f8f0933e9d47539ebc37163157499f":{
      "scriptId":"u13"},
    "ef8357f3f83d46a3820c55dc87ef67db":{
      "scriptId":"u14"},
    "b68082fd583d44b9bcee640ec6e56ef9":{
      "scriptId":"u15"},
    "c6cc88e661d848e5a1554c0b6a2ead59":{
      "scriptId":"u16"},
    "d167eea33bd44d4696db010ebdde1898":{
      "scriptId":"u17"},
    "5a4da6d487ce41e4bf8147d535012473":{
      "scriptId":"u18"},
    "e264d493531e4eb59886bdc8a8f220bd":{
      "scriptId":"u19"},
    "8bd035d5098644619ba39532521d1e44":{
      "scriptId":"u20"},
    "8f5b4aa44c5c430ebed37f77961fc5b0":{
      "scriptId":"u21"},
    "0db8235c4c0740c18ead97c02b9cccc6":{
      "scriptId":"u22"},
    "59abf7dfbb0c420291c124016c3dd0c0":{
      "scriptId":"u23"},
    "4e291fed272e436db5efd5cc59a86988":{
      "scriptId":"u24"},
    "0788fa1e532b48abbdc829f773ea8a0f":{
      "scriptId":"u25"},
    "c57fa25fe0704b9ab2b4f6631a73288c":{
      "scriptId":"u26"},
    "dd35e27c78854147a0df504b516ec91e":{
      "scriptId":"u27"},
    "f3ab2257012a4442b44ddb8ab60d407f":{
      "scriptId":"u28"},
    "4a12459fb3114deea1b011582105e093":{
      "scriptId":"u29"},
    "5279ea82b9af40488362c2dca92223f5":{
      "scriptId":"u30"},
    "15482e478480446e8b3ae8b58766b9e3":{
      "scriptId":"u31"},
    "efafcbcfb10a47e88147b67f06c68da5":{
      "scriptId":"u32"},
    "faa04e5bf32c400c9188406dabb624bc":{
      "scriptId":"u33"},
    "0be1d8b6c9f54b5b89e0045bd7611c2a":{
      "scriptId":"u34"},
    "4b91c162f72a432ebed29e7ba8345ebc":{
      "scriptId":"u35"},
    "5c682ebf65a94c76a0d3b8612faec67a":{
      "scriptId":"u36"},
    "f889c70deaed4a09b93d053384bd3902":{
      "scriptId":"u37"},
    "50cf14a30ba34ab981371fb8b7e53ada":{
      "scriptId":"u38"},
    "42f7d0697c59400a9adc2e9fe2223aff":{
      "scriptId":"u39"},
    "8bb36898ffbd4557aa06093c6c11f94a":{
      "scriptId":"u40"},
    "c07c2ca677e84910aaddab4a463c553a":{
      "scriptId":"u41"},
    "c91f26a4b8f544a888921a16f2eaa03c":{
      "scriptId":"u42"},
    "3cd4d89ea4484e3caedd41955e55db55":{
      "scriptId":"u43"},
    "bd4f65c1c11243e1904b52c642e2229f":{
      "scriptId":"u44"},
    "52456c50c94a470ca75b3bc83a643935":{
      "scriptId":"u45"},
    "5aade02f10d14050959f3f1da88d855b":{
      "scriptId":"u46"},
    "484ba5786ce34349b200ecdf3324cfe4":{
      "scriptId":"u47"},
    "5aa470a58861432781961700e291c89d":{
      "scriptId":"u48"},
    "f8b897923c284efa86a50eeaa6ef96e6":{
      "scriptId":"u49"},
    "789f2f4d5169440081e64d795795eb3e":{
      "scriptId":"u50"},
    "45ed29b505304a4d9ea0746ffdda06d2":{
      "scriptId":"u51"},
    "7722802fa5704f9d81f56dcc8b49bfa5":{
      "scriptId":"u52"},
    "7c699c9ea18d425dbea838c956cae877":{
      "scriptId":"u53"}}});